# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('expose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_title',
            field=models.CharField(default='A Non Creative Article', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='article_media_type',
            field=models.CharField(default=datetime.datetime(2017, 11, 3, 20, 4, 8, 945848, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
